prevent crash when igniting portal
Happens when trying to ignite a portal to the cloudlands, but the cloudlands mod hasn't inited yet because it hasn't needed to generate any islands:

ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'default' in callback item_OnPlace(): ...\minetest-5 latest\bin\..\mods\cloudlands/cloudlands.lua:591: attempt to index upvalue 'noise_heightMap' (a nil value)
stack traceback:
	...\minetest-5 latest\bin\..\mods\cloudlands/cloudlands.lua:591: in function 'is_within_realm'
	...ble)\minetest-5 latest\bin\..\mods\nether/portal_api.lua:1356: in function 'ignite_portal'
	...ble)\minetest-5 latest\bin\..\mods\nether/portal_api.lua:2159: in function <...ble)\minetest-5 latest\bin\..\mods\nether/portal_api.lua:2156>